name: Build

on: push

jobs:
  gradle:
    strategy:
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install GCC-Multilib
        run: sudo apt-get install gcc-multilib
        if: matrix.os == 'ubuntu-latest'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: current
      - name: Execute Gradle build
        run: ./gradlew natives:actionsBuild
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: native
          # path: natives/build/output
          # TODO:
          path: natives/build/lib/main/debug/
