name: Build

on: [workflow_dispatch, push]

defaults:
  run:
    shell: bash

jobs:
  windows:
    name: Compile and Link for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Make Directory
        run: mkdir windows
      - name: Compile
        run: g++ -c -I$JAVA_HOME/include -I$JAVA_HOME/include/win32 src/main/cpp/zone_rong_imaginebreaker_NativeImagineBreaker.cpp -o windows/zone_rong_imaginebreaker_NativeImagineBreaker.o
      - name: Linking
        run: g++ -shared -o output_natives/imaginebreaker.dll windows/zone_rong_imaginebreaker_NativeImagineBreaker.o -Wl,--add-stdcall-alias
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-${{ matrix.os }}
          path: output_natives/
  linux:
    name: Compile and Link for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Make Directory
        run: mkdir linux
      - name: Compile
        run: g++ -c -fPIC -I$JAVA_HOME/include -I$JAVA_HOME/include/linux src/main/cpp/zone_rong_imaginebreaker_NativeImagineBreaker.cpp -o linux/zone_rong_imaginebreaker_NativeImagineBreaker.o
      - name: Linking
        run: g++ -shared -fPIC -o output_natives/imaginebreaker.so linux/zone_rong_imaginebreaker_NativeImagineBreaker.o -lc
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-${{ matrix.os }}
          path: output_natives/
  osx:
    name: Compile and Link for MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Make Directory
        run: mkdir macos
      - name: Compile
        run: g++ -c -fPIC -I$JAVA_HOME/include -I$JAVA_HOME/include/darwin src/main/cpp/zone_rong_imaginebreaker_NativeImagineBreaker.cpp -o macos/zone_rong_imaginebreaker_NativeImagineBreaker.o
      - name: Linking
        run: g++ -dynamiclib -o output_natives/imaginebreaker.dylib macos/zone_rong_imaginebreaker_NativeImagineBreaker.o -lc
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-${{ matrix.os }}
          path: output_natives/
          
  build-jar:
    name: Compile Jar
    runs-on: windows-latest
    needs: [windows, linux, osx]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: actions/download-artifact@v3
        with:
          path: src/main/resources
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle Build (Skip Tests)
        run: ./gradlew build -x test
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ImagineBreaker-${{ matrix.os }}
          path: build/libs/
