name: Build

on: push

env:
  LIB_NAME: libImagineBreaker
  PATH_TO_CODE: natives/src/main/c/zone_rong_imaginebreaker_ImagineBreaker

jobs:
  linux_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile
        run: |
          gcc -c -fPIC -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux $PATH_TO_CODE.c -o $PATH_TO_CODE_x64.o

      - name: Link
        run: |
          gcc -shared -fPIC -o /lib/linux/$LIB_NAME_x64.so $PATH_TO_CODE_x64.o -lc
          
      - name: Upload Natives
        uses: actions/upload-artifact@v3
        with:
          name: native
          path: /lib/linux/