name: Build

on: push

env:
  LIB_NAME: libImagineBreaker
  PATH_TO_CODE: natives/src/main/c/zone_rong_imaginebreaker_ImagineBreaker

jobs:
  linux_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Directory
        run: mkdir output

      - name: Compile
        run: |
          gcc -c -fPIC -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux ${{ env.PATH_TO_CODE }}.c -o ${{ env.PATH_TO_CODE }}_x64.o
          gcc -m32 -c -fPIC -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux ${{ env.PATH_TO_CODE }}.c -o ${{ env.PATH_TO_CODE }}_x86.o

      - name: Link
        run: |
          gcc -shared -fPIC -o output/${{ env.LIB_NAME }}_x64.so ${{ env.PATH_TO_CODE }}_x64.o -lc
          gcc -shared -fPIC -o output/${{ env.LIB_NAME }}_x86.so ${{ env.PATH_TO_CODE }}_x86.o -lc

      - name: Upload Natives
        uses: actions/upload-artifact@v3
        with:
          name: native
          path: output/